In [1]:
import numpy as np

In [9]:
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr)) 

arr2=np.array([1,2,3,4,5,"prime"])
print(arr2 ,type(arr2),arr2.dtype)


arr3=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr3)
print(arr3.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [17]:
#create an from scratch

arr1=np.zeros((2,3) ,dtype="int64") #prefill
print(arr1,arr1.shape)

arr2=np.ones((2,3)) #prefill


print(arr2,arr2.shape)

arr3=np.full((3,4) ,100) #prefill the value(100)
print(arr3,arr3.shape)

arr4=np.eye((3)) #create an identity matrix
print(arr4)




[[0 0 0]
 [0 0 0]] (2, 3)
[[1. 1. 1.]
 [1. 1. 1.]] (2, 3)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
