In [1]:
import numpy as np

arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr)) 

arr2=np.array([1,2,3,4,5,"prime"])
print(arr2 ,type(arr2),arr2.dtype)


arr3=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr3)
print(arr3.shape)

In [2]:
#create an from scratch

arr1=np.zeros((2,3) ,dtype="int64") #prefill
print(arr1,arr1.shape)

arr2=np.ones((2,3)) #prefill


print(arr2,arr2.shape)

arr3=np.full((3,4) ,100) #prefill the value(100)
print(arr3,arr3.shape)

arr4=np.eye((3)) #create an identity matrix
print(arr4)

#arange is basiclly range function (start,end,gap)
arr5=np.arange(1,10,2)
print(arr5)




[[0 0 0]
 [0 0 0]] (2, 3)
[[1. 1. 1.]
 [1. 1. 1.]] (2, 3)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]] (3, 4)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1 3 5 7 9]


In [3]:
#properties

arr=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr.shape) #dimension of the array=m x n
print(arr.size) #total elements 9
print(arr.dtype)
print(arr.ndim)

float_arr=arr.astype(np.float64)
print(float_arr,float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [4]:
#operation on numpy array 

#1 reashping

##change the or we can say transpose the array

arr=np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)

reshaped=arr.reshape((3,2))
print(reshaped,reshaped.shape)

flattend=arr.flatten() #covert 2d array in 1d 
print(flattend,flattend.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [5]:
#2 indexing 

arr=np.array([1,2,3,4,5])

print(arr[0])

1


In [6]:
#3 boolean indexing 
arr=np.array([1,2,3,4,5])

print(arr[arr>2])
print(arr[arr%2==0])
print(arr[arr%2 !=0])

[3 4 5]
[2 4]
[1 3 5]


In [7]:
#4 slicing 

arr=np.array([1,2,3,4,5])
print(arr[1:4])# [start,end,step]
print(arr[1:])
      

[2 3 4]
[2 3 4 5]


multi dimensional Array

In [8]:
arr2d= np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr2d)
print(np.sum(arr2d))

sum_of_coloums=np.sum(arr2d,axis=0)
print(sum_of_coloums)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]


In [9]:
#3d array

arr=np.array([ [[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]] ]) #2 x3x2
print(arr)

print(arr[0,1,1])

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
4
